version: "3.3"

services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - ~/mongo/data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 321654
        ports:
            - 27017:27017
