version: '3.3'
services:
    fluid-b:
        container_name: FLUID-SERVICE-B
        image: flycamsafety/fluid-b:latest
        restart: always
        platform: linux/amd64
        cpus: 0.5
        mem_reservation: "50M"
        mem_limit: "250M"
        environment:
            # RabbitMQ
            - RABBITMQ_HOST=localhost
            - RABBITMQ_AMQP_PORT=5672
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_VHOST=/
            - QUEUE_RCV_PROCESSING=fluid-processing-I
        build:
            dockerfile: ./Dockerfile
